---
  - name: 'adiciona repo do php5.6'
    apt_repository:
      repo: ppa:ondrej/php
      update_cache: yes
      state: present
    become: yes

  - name: 'Instala pacotes de dependencia do sistema operacional'
    apt:
      name: ['php5.6', 'apache2', 'libapache2-mod-php5.6', 'php5.6-gd','php5.6-mysql']
      state: latest
    become: yes

  - name: 'Baixando wordpress'
    get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'

  - name: 'Descompactando o wordpress'
    unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: '/var/www/'
        remote_src: yes
    become: yes
  
  - name: 'Configurando o wordpress'
    copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
    become: yes
    
  - name: 'Configurando wordpress_db'
    replace:
        path: '/var/www/wordpress/wp-config.php'
        regexp: '{{ item.regex }}'
        replace: '{{ item.value }}'
        backup: yes
    with_items:
      - { regex: 'database_name_here', value: 'wordpress_db'}
      - { regex: 'username_here', value: 'vagrant'}
      - { regex: 'password_here', value: '12345'}
      - { regex: 'localhost', value: '172.17.177.52'}
    become: yes


  - name: 'Configurando apache'
    copy:
      src: 'files/000-default.conf'
      dest: '/etc/apache2/sites-available/000-default.conf'
    become: yes
    notify:
      - restart apache