---
  - name: 'adiciona repo do php5.6'
    apt_repository:
      repo: ppa:ondrej/php
      update_cache: yes
      state: present
    become: yes

  - name: 'Instala pacotes de dependencia do sistema operacional'
    apt:
      name: ['php5.6', 'apache2', 'libapache2-mod-php5.6', 'php5.6-gd', 'mysql-server', 'python-mysqldb', 'php5.6-mysql']
      state: latest
    become: yes
  
  - name: 'Cria banco de testes'
    mysql_db:
        name: wordpress_db
        login_user: root
        state: present
    become: yes

  - name: 'Cria o usuario do mysql'
    mysql_user:
        name: vagrant
        password: '12345'
        priv: 'wordpress_db.*:ALL'
        state: present
    become: yes